### ISSUE TITLE
Compile fails on Mac OS X 10.6

### ISSUE THREAD

**Issue by ryandesign** [BlueM/cliclick#14]
Hello, I'm the maintainer of cliclick in MacPorts and I recently updated our port to 3.0.2. It doesn't build for us on Mac OS X 10.6. We see errors like:

```
KeycodeInformer.m:48: error: expected ')' before 'instancetype'
```

and:

```
Actions/KeyBaseAction.m:36: error: expected expression before '@' token
```

Curiously, although your web page lists 10.6 or later as a requirement, it builds fine on Mac OS X 10.4.
